# Generated by Django 5.0.1 on 2024-01-16 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortenerTable",
            fields=[
                ("visit_count", models.PositiveIntegerField(default=0)),
                (
                    "short_url",
                    models.CharField(
                        default="", max_length=100, primary_key=True, serialize=False
                    ),
                ),
                ("original_url", models.CharField(default="", max_length=1000)),
                ("created_by", models.CharField(default="Anonymous", max_length=255)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "expiry_date",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 1, 19, 22, 12, 20, 86642)
                    ),
                ),
            ],
        ),
    ]
