# Generated by Django 5.0.1 on 2024-01-16 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0006_alter_shortenertable_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortenertable",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 19, 18, 53, 54, 188079, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
