# Generated by Django 5.0.1 on 2024-01-16 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0008_alter_shortenertable_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortenertable",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 19, 19, 18, 25, 684446, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
